version: '3'

services:
  mysql_db:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 123456